change travis

diff --git a/travis/run_on_pull_requests b/travis/run_on_pull_requests
--- a/travis/run_on_pull_requests
+++ b/travis/run_on_pull_requests
@@ -1,34 +1,19 @@
 #!/bin/bash
+
+# goimports test
 diff <(goimports -d $(find . -type f -name '*.go' -not -path "*/vendor/*")) <(printf "")
 
-echo "goimports processing..."
 if [ $? -ne 0 ]; then
-  echo "goimports format error" >&2
-  exit 1
+echo "goimports format error" >&2
+exit 1
 fi
 
-#echo "go vet processing...."
-#go vet -v ./...
-
-#if [ $? -ne 0 ]; then
-#  echo "go vet fail" >&2
-#  exit 1
-#fi
-
-#echo "golangci-lint run processing...."
-#golangci-lint run       # run a bunch of code checkers/linters in parallel
-
-#if [ $? -ne 0 ]; then
-#  echo "golangci-lint fail" >&2
-#  exit 1
-#fi
-
-#echo "go test -p 1 -v -race ./... processing...."
-echo "go test -p 1 -v ./... processing...."
-#go test -p 1 -v -race ./... # Run all the tests with the race detector enabled
-go test -p 1 -v ./... # Run all the tests
+# run go test
+go test -v -mod=vendor ./...
 
 if [ $? -ne 0 ]; then
-  echo "go test fail" >&2
-  exit 1
+echo "go test fail" >&2
+exit 1
 fi
+
+exit 0
